/**
 * =========================================================================
 * EXPANDED SCIENTIFIC & FORENSIC ENTERPRISE DATASET
 * =========================================================================
 * Comprehensive realistic dataset for in silico molecular docking benchmarks,
 * drug-protein affinity evaluations, and field forensic custody testing.
 */

import type {
  Protein,
  Ligand,
  Case,
  Sample,
  FieldTest,
  Evidence,
  DockingJob,
  DockingResult,
} from '../types';

export const EXPANDED_PROTEINS: Protein[] = [
  // Infectious Disease Targets
  {
    id: 'prot_exp_001',
    name: 'SARS-CoV-2 Main Protease (Mpro)',
    structureId: '6LU7',
    description: 'Key homodimeric cysteine protease that cleaves viral polyproteins into functional units. Primary target for oral antivirals.',
    source: 'RCSB PDB Reference',
    fileName: '6LU7_prepared.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 348210,
    uploadDate: '2026-09-15T10:00:00Z',
    status: 'READY',
    organism: 'SARS-CoV-2',
    resolution: '2.16 Å',
  },
  {
    id: 'prot_exp_002',
    name: 'HIV-1 Retropepsin Protease',
    structureId: '1HSG',
    description: 'Aspartyl protease essential for the viral life cycle and maturation of infectious virions. Classical target in HAART therapy.',
    source: 'RCSB PDB Reference',
    fileName: '1HSG_receptor.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 284100,
    uploadDate: '2026-09-16T14:30:00Z',
    status: 'READY',
    organism: 'Human immunodeficiency virus 1',
    resolution: '2.00 Å',
  },
  {
    id: 'prot_exp_003',
    name: 'SARS-CoV-2 RNA-Dependent RNA Polymerase',
    structureId: '7BV2',
    description: 'Catalytic core complex of nsp12-nsp7-nsp8 involved in replicating the viral viral genome, complexed with Remdesivir monophosphate.',
    source: 'RCSB PDB Reference',
    fileName: '7BV2_rdrp.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 452100,
    uploadDate: '2026-09-18T09:15:00Z',
    status: 'READY',
    organism: 'SARS-CoV-2',
    resolution: '2.50 Å',
  },
  {
    id: 'prot_exp_004',
    name: 'Influenza A Neuraminidase (N1)',
    structureId: '2HU4',
    description: 'Enzyme facilitating viral release from infected host cells by cleaving terminal sialic acid residues. Target of Oseltamivir.',
    source: 'RCSB PDB Reference',
    fileName: '2HU4_neuraminidase.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 395400,
    uploadDate: '2026-09-18T11:45:00Z',
    status: 'READY',
    organism: 'Influenza A virus (H5N1)',
    resolution: '2.50 Å',
  },
  {
    id: 'prot_exp_005',
    name: 'Hepatitis C Virus NS3/4A Protease',
    structureId: '1DY8',
    description: 'Serine protease critical for viral replication and immune response suppression. Target for direct-acting antivirals (DAAs).',
    source: 'RCSB PDB Reference',
    fileName: '1DY8_hcv_protease.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 312000,
    uploadDate: '2026-09-19T08:00:00Z',
    status: 'READY',
    organism: 'Hepatitis C virus',
    resolution: '2.50 Å',
  },

  // Oncology Targets
  {
    id: 'prot_exp_006',
    name: 'Epidermal Growth Factor Receptor (EGFR) Kinase',
    structureId: '1M17',
    description: 'Tyrosine kinase receptor domain frequently mutated in non-small cell lung cancer. Target of Erlotinib, Gefitinib, and Osimertinib.',
    source: 'RCSB PDB Reference',
    fileName: '1M17_egfr_kinase.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 382400,
    uploadDate: '2026-09-20T12:00:00Z',
    status: 'READY',
    organism: 'Homo sapiens',
    resolution: '2.60 Å',
  },
  {
    id: 'prot_exp_007',
    name: 'BCR-ABL Tyrosine Kinase Domain',
    structureId: '1IEP',
    description: 'Oncogenic fusion protein driving chronic myelogenous leukemia (CML). Classic landmark target inhibited by Imatinib (Gleevec).',
    source: 'RCSB PDB Reference',
    fileName: '1IEP_bcr_abl.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 367200,
    uploadDate: '2026-09-20T14:20:00Z',
    status: 'READY',
    organism: 'Homo sapiens',
    resolution: '2.10 Å',
  },
  {
    id: 'prot_exp_008',
    name: 'Estrogen Receptor Alpha (ER-alpha) LBD',
    structureId: '3ERT',
    description: 'Nuclear receptor ligand-binding domain involved in hormone-dependent breast carcinoma, shown in complex with 4-Hydroxytamoxifen.',
    source: 'RCSB PDB Reference',
    fileName: '3ERT_er_alpha.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 320400,
    uploadDate: '2026-09-21T10:10:00Z',
    status: 'READY',
    organism: 'Homo sapiens',
    resolution: '1.90 Å',
  },
  {
    id: 'prot_exp_009',
    name: 'Poly [ADP-Ribose] Polymerase 1 (PARP-1)',
    structureId: '4ZZZ',
    description: 'DNA damage sensor facilitating single-strand break repair. Key synthetic lethality target in BRCA1/2-deficient malignancies.',
    source: 'RCSB PDB Reference',
    fileName: '4ZZZ_parp1.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 412800,
    uploadDate: '2026-09-21T16:00:00Z',
    status: 'READY',
    organism: 'Homo sapiens',
    resolution: '2.20 Å',
  },
  {
    id: 'prot_exp_010',
    name: 'BRAF V600E Kinase Domain',
    structureId: '4MNE',
    description: 'Constitutively active oncogenic serine/threonine-protein kinase driving cutaneous melanoma. Bound to Vemurafenib.',
    source: 'RCSB PDB Reference',
    fileName: '4MNE_braf.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 350100,
    uploadDate: '2026-09-22T08:30:00Z',
    status: 'READY',
    organism: 'Homo sapiens',
    resolution: '2.45 Å',
  },

  // Neurology, Toxicology & Forensic Receptors
  {
    id: 'prot_exp_011',
    name: 'Human Acetylcholinesterase (AChE)',
    structureId: '4EY7',
    description: 'Cholinesterase hydrolyzing acetylcholine at neuromuscular junctions. Target of nerve agents, organophosphates, and Alzheimer therapeutics.',
    source: 'RCSB PDB Reference',
    fileName: '4EY7_ache.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 498300,
    uploadDate: '2026-09-22T13:40:00Z',
    status: 'READY',
    organism: 'Homo sapiens',
    resolution: '2.35 Å',
  },
  {
    id: 'prot_exp_012',
    name: 'Mu-Opioid Receptor (MOR)',
    structureId: '4DKL',
    description: 'G-protein coupled receptor mediating analgesia, euphoria, and respiratory depression. High-affinity target of morphine and fentanyl.',
    source: 'RCSB PDB Reference',
    fileName: '4DKL_mu_opioid.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 410200,
    uploadDate: '2026-09-23T09:00:00Z',
    status: 'READY',
    organism: 'Mus musculus / Homo sapiens chimera',
    resolution: '2.80 Å',
  },
  {
    id: 'prot_exp_013',
    name: 'Cannabinoid Receptor 1 (CB1)',
    structureId: '5XRA',
    description: 'Central nervous system GPCR regulating neurotransmitter release. Receptor target for phytocannabinoids (THC, CBD) and synthetic agonists.',
    source: 'RCSB PDB Reference',
    fileName: '5XRA_cb1.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 399100,
    uploadDate: '2026-09-23T11:20:00Z',
    status: 'READY',
    organism: 'Homo sapiens',
    resolution: '2.80 Å',
  },
  {
    id: 'prot_exp_014',
    name: 'Dopamine D2 Receptor (D2R)',
    structureId: '6CM4',
    description: 'Principal G-protein coupled target for typical/atypical antipsychotics and psychostimulant regulatory pathways.',
    source: 'RCSB PDB Reference',
    fileName: '6CM4_d2r.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 388700,
    uploadDate: '2026-09-23T15:00:00Z',
    status: 'READY',
    organism: 'Homo sapiens',
    resolution: '2.87 Å',
  },
  {
    id: 'prot_exp_015',
    name: 'Cytochrome P450 3A4 (CYP3A4)',
    structureId: '1TQN',
    description: 'Major hepatic and intestinal phase-I drug-metabolizing monooxygenase responsible for clearance of over 50% of clinical pharmaceuticals.',
    source: 'RCSB PDB Reference',
    fileName: '1TQN_cyp3a4.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 442500,
    uploadDate: '2026-09-24T08:15:00Z',
    status: 'READY',
    organism: 'Homo sapiens',
    resolution: '2.05 Å',
  },
  {
    id: 'prot_exp_016',
    name: 'Cyclooxygenase-2 (COX-2)',
    structureId: '1CX2',
    description: 'Inducible prostaglandin-endoperoxide synthase responsible for pro-inflammatory eicosanoid cascade. Target of NSAIDs and Celecoxib.',
    source: 'RCSB PDB Reference',
    fileName: '1CX2_cox2.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 478200,
    uploadDate: '2026-09-24T14:30:00Z',
    status: 'READY',
    organism: 'Mus musculus',
    resolution: '3.00 Å',
  },
  {
    id: 'prot_exp_017',
    name: 'Bacterial DNA Gyrase B Subunit',
    structureId: '1KZN',
    description: 'Type II topoisomerase essential for introducing negative supercoils into bacterial double-stranded DNA during replication.',
    source: 'RCSB PDB Reference',
    fileName: '1KZN_gyrase_b.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 325400,
    uploadDate: '2026-09-25T10:00:00Z',
    status: 'READY',
    organism: 'Escherichia coli',
    resolution: '2.30 Å',
  },
  {
    id: 'prot_exp_018',
    name: 'Human Dihydrofolate Reductase (DHFR)',
    structureId: '1DLS',
    description: 'Reduces dihydrofolic acid to tetrahydrofolic acid for purine synthesis. Inhibited by Methotrexate and Pyrimethamine.',
    source: 'RCSB PDB Reference',
    fileName: '1DLS_dhfr.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 260300,
    uploadDate: '2026-09-25T11:45:00Z',
    status: 'READY',
    organism: 'Homo sapiens',
    resolution: '1.70 Å',
  },
  {
    id: 'prot_exp_019',
    name: 'Serotonin 5-HT2A Receptor',
    structureId: '6A93',
    description: 'GPCR mediating psychedelic neurotransmission, mood regulation, and vascular tone. Bound to Risperidone.',
    source: 'RCSB PDB Reference',
    fileName: '6A93_5ht2a.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 405600,
    uploadDate: '2026-09-26T09:20:00Z',
    status: 'READY',
    organism: 'Homo sapiens',
    resolution: '3.00 Å',
  },
  {
    id: 'prot_exp_020',
    name: 'K-Ras Proto-Oncogene G12C Mutant',
    structureId: '6OIM',
    description: 'Small GTPase harboring oncogenic G12C switch-II pocket mutation. High-value target for covalent inhibitors like Sotorasib.',
    source: 'RCSB PDB Reference',
    fileName: '6OIM_kras_g12c.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 298400,
    uploadDate: '2026-09-26T16:10:00Z',
    status: 'READY',
    organism: 'Homo sapiens',
    resolution: '1.80 Å',
  },
];

export const EXPANDED_LIGANDS: Ligand[] = [
  // Antivirals & Protease Inhibitors
  {
    id: 'lig_exp_001',
    name: 'Nirmatrelvir (Paxlovid)',
    chemicalName: '(1R,2S,5S)-N-((1S)-1-cyano-2-((3S)-2-oxopyrrolidin-3-yl)ethyl)-3-((2S)-3,3-dimethyl-2-(2,2,2-trifluoroacetamido)butanoyl)-6,6-dimethyl-3-azabicyclo[3.1.0]hexane-2-carboxamide',
    formula: 'C23H32F3N5O4',
    smiles: 'CC(C)(C)C(NC(=O)C(F)(F)F)C(=O)N1CC2C(C1C(=O)NC(CC3CCNC3=O)C#N)C2(C)C',
    molecularWeight: 499.53,
    isDemo: false,
    uploadDate: '2026-09-15T12:00:00Z',
    status: 'READY',
    description: 'Potent peptidomimetic inhibitor targeting SARS-CoV-2 Mpro active site cysteine Cys145.',
  },
  {
    id: 'lig_exp_002',
    name: 'Remdesivir (GS-5734)',
    chemicalName: '2-ethylbutyl (2S)-2-[[[(2R,3S,4R,5R)-5-(4-aminopyrrolo[2,1-f][1,2,4]triazin-7-yl)-5-cyano-3,4-dihydroxyoxolan-2-yl]methoxy-phenoxyphosphoryl]amino]propanoate',
    formula: 'C27H35N6O8P',
    smiles: 'CCC(CC)COC(=O)C(C)NP(=O)(OCC1C(C(C(O1)(C#N)C2=CC=C3N2N=CN=C3N)O)O)OC4=CC=CC=C4',
    molecularWeight: 602.58,
    isDemo: false,
    uploadDate: '2026-09-16T10:00:00Z',
    status: 'READY',
    description: 'Broad-spectrum monophosphoramidate prodrug nucleotide analog targeting viral RNA-dependent RNA polymerase.',
  },
  {
    id: 'lig_exp_003',
    name: 'Indinavir (Crixivan)',
    chemicalName: '(2S)-1-[(2S,4R)-4-benzyl-2-hydroxy-5-[[(1S,2R)-2-hydroxy-2,3-dihydro-1H-inden-1-yl]amino]-5-oxopentyl]-N-tert-butyl-4-(pyridin-3-ylmethyl)piperazine-2-carboxamide',
    formula: 'C36H47N5O4',
    smiles: 'CC(C)(C)NC(=O)C1CN(CCN1CC2=CN=CC=C2)CC(CC(CC3=CC=CC=C3)C(=O)NC4C(CC5=CC=CC=C54)O)O',
    molecularWeight: 613.79,
    isDemo: false,
    uploadDate: '2026-09-17T09:00:00Z',
    status: 'READY',
    description: 'Transition-state peptidomimetic inhibitor of HIV-1 protease with high binding affinity and clinical history.',
  },
  {
    id: 'lig_exp_004',
    name: 'Oseltamivir Carboxylate (Tamiflu Active)',
    chemicalName: '(3R,4R,5S)-4-acetamido-5-amino-3-(pentan-3-yloxy)cyclohex-1-ene-1-carboxylic acid',
    formula: 'C14H24N2O4',
    smiles: 'CCC(CC)OC1C=C(CC(C1NC(=O)C)N)C(=O)O',
    molecularWeight: 284.35,
    isDemo: false,
    uploadDate: '2026-09-18T14:00:00Z',
    status: 'READY',
    description: 'Competitive active site inhibitor of viral neuraminidase, preventing viral egress from host epithelial cells.',
  },

  // Targeted Oncology Small Molecules
  {
    id: 'lig_exp_005',
    name: 'Imatinib (Gleevec)',
    chemicalName: '4-[(4-methylpiperazin-1-yl)methyl]-N-[4-methyl-3-[(4-pyridin-3-ylpyrimidin-2-yl)amino]phenyl]benzamide',
    formula: 'C29H31N7O',
    smiles: 'CC1=C(C=C(C=C1)NC(=O)C2=CC=C(C=C2)CN3CCN(CC3)C)NC4=NC=CC(=N4)C5=CN=CC=C5',
    molecularWeight: 493.60,
    isDemo: false,
    uploadDate: '2026-09-19T11:00:00Z',
    status: 'READY',
    description: 'First-in-class small-molecule 2-phenylaminopyrimidine kinase inhibitor targeting BCR-ABL, c-KIT, and PDGFR.',
  },
  {
    id: 'lig_exp_006',
    name: 'Osimertinib (Tagrisso)',
    chemicalName: 'N-[2-[[2-(dimethylamino)ethyl]-methylamino]-4-methoxy-5-[[4-(1-methylindol-3-yl)pyrimidin-2-yl]amino]phenyl]prop-2-enamide',
    formula: 'C28H33N7O2',
    smiles: 'CN(C)CCN(C)C1=C(C=C(C(=C1)NC(=O)C=C)NC2=NC=CC(=N2)C3=CN(C4=CC=CC=C43)C)OC',
    molecularWeight: 499.61,
    isDemo: false,
    uploadDate: '2026-09-20T10:30:00Z',
    status: 'READY',
    description: 'Third-generation irreversible mutant-selective EGFR T790M and L858R tyrosine kinase inhibitor.',
  },
  {
    id: 'lig_exp_007',
    name: 'Olaparib (Lynparza)',
    chemicalName: '4-[(3-{[4-(cyclopropylcarbonyl)piperazin-1-yl]carbonyl}-4-fluorophenyl)methyl]phthalazin-1(2H)-one',
    formula: 'C24H23FN4O3',
    smiles: 'O=C(C1CC1)N2CCN(CC2)C(=O)C3=CC(CC4=NNC(=O)C5=CC=CC=C45)=CC=C3F',
    molecularWeight: 434.46,
    isDemo: false,
    uploadDate: '2026-09-20T16:00:00Z',
    status: 'READY',
    description: 'Crystallographically validated PARP-1 and PARP-2 catalytic domain inhibitor for homologous recombination repair-deficient tumors.',
  },
  {
    id: 'lig_exp_008',
    name: 'Vemurafenib (Zelboraf)',
    chemicalName: 'N-[3-[[5-(4-chlorophenyl)-1H-pyrrolo[2,3-b]pyridin-3-yl]carbonyl]-2,4-difluorophenyl]propane-1-sulfonamide',
    formula: 'C23H18ClF2N3O3S',
    smiles: 'CCCS(=O)(=O)NC1=C(C=CC(=C1F)C(=O)C2=CNC3=C2C=C(C=N3)C4=CC=C(C=C4)Cl)F',
    molecularWeight: 489.92,
    isDemo: false,
    uploadDate: '2026-09-21T09:30:00Z',
    status: 'READY',
    description: 'Conformation-selective ATP-competitive inhibitor of mutated BRAF V600E oncogenic monomeric kinase.',
  },

  // Forensic Reference Standards, Antidotes & Controlled Substances
  {
    id: 'lig_exp_009',
    name: 'Fentanyl Reference Standard (Control)',
    chemicalName: 'N-(1-(2-phenylethyl)-4-piperidinyl)-N-phenylpropanamide',
    formula: 'C22H28N2O',
    smiles: 'CCC(=O)N(C1=CC=CC=C1)C2CCN(CCC3=CC=CC=C3)CC2',
    molecularWeight: 336.47,
    isDemo: false,
    uploadDate: '2026-09-22T08:00:00Z',
    status: 'READY',
    description: '[AUTHORIZED FORENSIC REFERENCE STANDARD] Mu-opioid receptor selective high-potency ligand for field assay calibration.',
  },
  {
    id: 'lig_exp_010',
    name: 'Naloxone (Narcan Antagonist)',
    chemicalName: '(4R,4aS,7aR,12bS)-4a,9-dihydroxy-3-(prop-2-en-1-yl)-2,4,5,6,7a,13-hexahydro-1H-4,12-methanobenzofuro[3,2-e]isoquinolin-7-one',
    formula: 'C19H21NO4',
    smiles: 'C=CCN1CCC23C4C1CC5=C2C(=C(C=C5)O)OC3C(=O)CCC4(O)O',
    molecularWeight: 327.37,
    isDemo: false,
    uploadDate: '2026-09-22T10:00:00Z',
    status: 'READY',
    description: 'Competitive mu, kappa, and delta opioid receptor antagonist used as life-saving overdose emergency countermeasure.',
  },
  {
    id: 'lig_exp_011',
    name: 'Morphine Standard',
    chemicalName: '(4R,4aR,7S,7aR,12bS)-3-methyl-2,4,4a,7,7a,13-hexahydro-1H-4,12-methanobenzofuro[3,2-e]isoquinoline-7,9-diol',
    formula: 'C17H19NO3',
    smiles: 'CN1CCC23C4C1CC5=C2C(=C(C=C5)O)OC3C(C=C4)O',
    molecularWeight: 285.34,
    isDemo: false,
    uploadDate: '2026-09-22T14:30:00Z',
    status: 'READY',
    description: '[FORENSIC STANDARD] Natural phenanthrene opiate alkaloid reference standard for comparative chromatography and receptor binding.',
  },
  {
    id: 'lig_exp_012',
    name: 'Methamphetamine Standard (Reference)',
    chemicalName: '(2S)-N-methyl-1-phenylpropan-2-amine',
    formula: 'C10H15N',
    smiles: 'CC(CC1=CC=CC=C1)NC',
    molecularWeight: 149.23,
    isDemo: false,
    uploadDate: '2026-09-23T08:30:00Z',
    status: 'READY',
    description: '[FORENSIC CALIBRATION COMPOUND] Synthetic substituted phenethylamine psychostimulant reference for field reagent validation.',
  },
  {
    id: 'lig_exp_013',
    name: 'Cannabidiol (CBD)',
    chemicalName: '2-[(1R,6R)-6-isopropenyl-3-methylcyclohex-2-en-1-yl]-5-pentylbenzene-1,3-diol',
    formula: 'C21H30O2',
    smiles: 'CCCCCC1=CC(=C(C(=C1)O)C2C=C(CCC2C(=C)C)C)O',
    molecularWeight: 314.46,
    isDemo: false,
    uploadDate: '2026-09-23T11:00:00Z',
    status: 'READY',
    description: 'Non-intoxicating phytocannabinoid negative allosteric modulator of CB1 and agonist of 5-HT1A receptors.',
  },
  {
    id: 'lig_exp_014',
    name: 'Donepezil (Aricept)',
    chemicalName: '(RS)-2-[(1-benzyl-4-piperidyl)methyl]-5,6-dimethoxy-2,3-dihydroinden-1-one',
    formula: 'C24H29NO3',
    smiles: 'COC1=C(C=C2C(=C1)CC(C2=O)CC3CCN(CC3)CC4=CC=CC=C4)OC',
    molecularWeight: 379.49,
    isDemo: false,
    uploadDate: '2026-09-24T09:00:00Z',
    status: 'READY',
    description: 'Reversible centrally active acetylcholinesterase inhibitor that binds to both the catalytic and peripheral anionic sites.',
  },
  {
    id: 'lig_exp_015',
    name: 'Diazepam (Valium Reference)',
    chemicalName: '7-chloro-1-methyl-5-phenyl-3H-1,4-benzodiazepin-2-one',
    formula: 'C16H13ClN2O',
    smiles: 'CN1C(=O)CN=C(C2=C1C=CC(=C2)Cl)C3=CC=CC=C3',
    molecularWeight: 284.74,
    isDemo: false,
    uploadDate: '2026-09-24T12:00:00Z',
    status: 'READY',
    description: 'Positive allosteric modulator of GABA-A receptor benzodiazepine binding site.',
  },
  {
    id: 'lig_exp_016',
    name: 'Ciprofloxacin (Cipro)',
    chemicalName: '1-cyclopropyl-6-fluoro-4-oxo-7-piperazin-1-ylquinoline-3-carboxylic acid',
    formula: 'C17H18FN3O3',
    smiles: 'C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O',
    molecularWeight: 331.34,
    isDemo: false,
    uploadDate: '2026-09-25T08:00:00Z',
    status: 'READY',
    description: 'Second-generation fluoroquinolone antibiotic targeting bacterial DNA gyrase and topoisomerase IV.',
  },
  {
    id: 'lig_exp_017',
    name: 'Ibuprofen',
    chemicalName: '(2RS)-2-[4-(2-methylpropyl)phenyl]propanoic acid',
    formula: 'C13H18O2',
    smiles: 'CC(C)CC1=CC=C(C=C1)C(C)C(=O)O',
    molecularWeight: 206.28,
    isDemo: false,
    uploadDate: '2026-09-25T11:00:00Z',
    status: 'READY',
    description: 'Non-steroidal anti-inflammatory drug (NSAID) acting as a non-selective inhibitor of COX-1 and COX-2.',
  },
  {
    id: 'lig_exp_018',
    name: 'Methotrexate',
    chemicalName: '(2S)-2-[[4-[(2,4-diaminopteridin-6-yl)methyl-methylamino]benzoyl]amino]pentanedioic acid',
    formula: 'C20H22N8O5',
    smiles: 'CN(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C=C3)C(=O)NC(CCC(=O)O)C(=O)O',
    molecularWeight: 454.44,
    isDemo: false,
    uploadDate: '2026-09-25T15:00:00Z',
    status: 'READY',
    description: 'Antimetabolite and antifolate agent competitively binding to human dihydrofolate reductase with sub-nanomolar affinity.',
  },
  {
    id: 'lig_exp_019',
    name: 'Sotorasib (AMG 510)',
    chemicalName: '6-fluoro-7-(2-fluoro-6-hydroxyphenyl)-(4M)-1-[4-methyl-2-(propan-2-yl)pyridin-3-yl]-4-[(2S)-2-methyl-4-(prop-2-enoyl)piperazin-1-yl]pyrido[2,3-d]pyrimidin-2(1H)-one',
    formula: 'C30H30F2N6O3',
    smiles: 'CC(C)C1=NC=CC(=C1N2C(=O)N=C3C(=C2C4=C(C=CC=C4F)O)N=C(C=C3F)N5CCN(CC5C)C(=O)C=C)C',
    molecularWeight: 560.60,
    isDemo: false,
    uploadDate: '2026-09-26T10:00:00Z',
    status: 'READY',
    description: 'First FDA-approved covalent small-molecule inhibitor of KRAS G12C, permanently locking it in the inactive GDP-bound state.',
  },
  {
    id: 'lig_exp_020',
    name: 'Aspirin (Acetylsalicylic Acid)',
    chemicalName: '2-acetyloxybenzoic acid',
    formula: 'C9H8O4',
    smiles: 'CC(=O)OC1=CC=CC=C1C(=O)O',
    molecularWeight: 180.16,
    isDemo: false,
    uploadDate: '2026-09-26T14:00:00Z',
    status: 'READY',
    description: 'Irreversible covalent inactivator of cyclooxygenase via acetylation of active-site Ser530.',
  },
];

export const EXPANDED_CASES: Case[] = [
  {
    id: 'case_exp_001',
    caseNumber: 'CASE-2026-TX-010',
    title: 'Interstate Bulk Pharmaceutical Interdiction',
    description: 'Interdiction of unmarked commercial cargo van containing 45 unlabelled containers of white crystalline powder on I-35 corridor.',
    status: 'TEST_COMPLETED',
    priority: 'CRITICAL',
    location: { address: 'I-35 Mile Marker 242, Austin, TX', latitude: 30.2672, longitude: -97.7431 },
    createdBy: 'usr_001',
    assignedOfficer: 'Specialist J. Miller',
    createdAt: '2026-09-01T08:30:00Z',
    updatedAt: '2026-09-01T15:20:00Z',
    notes: 'Presumptive screening indicates high-affinity synthetic opioid precursor. Chain of custody secured.',
  },
  {
    id: 'case_exp_002',
    caseNumber: 'CASE-2026-TX-011',
    title: 'Maritime Port Container Inspection #904',
    description: 'Customs and Border Protection flagged refrigerated container showing anomalous density scans in shipping bay C-12.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    location: { address: 'Port of Houston Terminal 4, Houston, TX', latitude: 29.7604, longitude: -95.3698 },
    createdBy: 'usr_002',
    assignedOfficer: 'Officer S. Chen',
    createdAt: '2026-09-03T10:15:00Z',
    updatedAt: '2026-09-03T18:00:00Z',
  },
  {
    id: 'case_exp_003',
    caseNumber: 'CASE-2026-TX-012',
    title: 'Suspected Clandestine Chemical Synthesis Site',
    description: 'Rural property warrant execution revealed dual reaction glassware, cooling manifolds, and unlabeled reagent carboys.',
    status: 'SAMPLE_COLLECTED',
    priority: 'CRITICAL',
    location: { address: 'Rural Route 14, Bastrop County, TX', latitude: 30.1105, longitude: -97.3153 },
    createdBy: 'usr_001',
    assignedOfficer: 'Specialist J. Miller',
    createdAt: '2026-09-05T06:45:00Z',
    updatedAt: '2026-09-05T14:10:00Z',
  },
  {
    id: 'case_exp_004',
    caseNumber: 'CASE-2026-TX-013',
    title: 'Airport Cargo Express Package Divergence',
    description: 'Suspicious air freight parcel arriving from overseas logistics hub manifested as analytical reagent samples.',
    status: 'UNDER_REVIEW',
    priority: 'MEDIUM',
    location: { address: 'DFW International Airport Logistics Hub, Dallas, TX', latitude: 32.8998, longitude: -97.0403 },
    createdBy: 'usr_003',
    assignedOfficer: 'Supervisor M. Vance',
    createdAt: '2026-09-07T11:00:00Z',
    updatedAt: '2026-09-08T09:30:00Z',
  },
  {
    id: 'case_exp_005',
    caseNumber: 'CASE-2026-TX-014',
    title: 'Counterfeit Prescription Tablet Distribution Ring',
    description: 'Undercover seizure of 12,000 pressed counterfeit blue tablets stamped M-30. Field testing required for active potent binders.',
    status: 'OPEN',
    priority: 'HIGH',
    location: { address: 'Warehouse District, San Antonio, TX', latitude: 29.4241, longitude: -98.4936 },
    createdBy: 'usr_002',
    assignedOfficer: 'Officer S. Chen',
    createdAt: '2026-09-10T14:00:00Z',
    updatedAt: '2026-09-10T16:45:00Z',
  },
  {
    id: 'case_exp_006',
    caseNumber: 'CASE-2026-TX-015',
    title: 'Contaminated Botanical Extract Analysis',
    description: 'Imported herbal supplement shipments suspected of adulteration with synthetic cannabinoid receptor agonists.',
    status: 'CLOSED',
    priority: 'LOW',
    location: { address: 'El Paso Border Inspection Station, El Paso, TX', latitude: 31.7619, longitude: -106.4850 },
    createdBy: 'usr_001',
    assignedOfficer: 'Specialist J. Miller',
    createdAt: '2026-09-12T09:00:00Z',
    updatedAt: '2026-09-14T17:00:00Z',
  },
  {
    id: 'case_exp_007',
    caseNumber: 'CASE-2026-TX-016',
    title: 'Industrial Solvent & Chemical Diversion Audit',
    description: 'Audit of chemical distributor sales logs showing diverted precursor quantities of acetic anhydride and piperidine.',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    location: { address: 'Corpus Christi Industrial Canal, Corpus Christi, TX', latitude: 27.8006, longitude: -97.3964 },
    createdBy: 'usr_003',
    assignedOfficer: 'Supervisor M. Vance',
    createdAt: '2026-09-15T13:20:00Z',
    updatedAt: '2026-09-16T11:15:00Z',
  },
  {
    id: 'case_exp_008',
    caseNumber: 'CASE-2026-TX-017',
    title: 'Field Test Kit Verification & Quality Control #88',
    description: 'Quarterly state forensic proficiency benchmark verifying multi-spectrum reagent kit colorimetric responsiveness.',
    status: 'CLOSED',
    priority: 'LOW',
    location: { address: 'State Forensic Oversight Lab #2, Austin, TX', latitude: 30.3000, longitude: -97.7500 },
    createdBy: 'usr_admin',
    assignedOfficer: 'Commander R. Reyes',
    createdAt: '2026-09-18T08:00:00Z',
    updatedAt: '2026-09-19T12:00:00Z',
  },
  {
    id: 'case_exp_009',
    caseNumber: 'CASE-2026-TX-018',
    title: 'Border Checkpoint Vehicle Concealment Seizure',
    description: 'Canine alert on commercial flatbed trailer leading to discovery of 18 heat-sealed foil packages concealed inside transmission casing.',
    status: 'TEST_COMPLETED',
    priority: 'CRITICAL',
    location: { address: 'US-59 Checkpoint, Laredo, TX', latitude: 27.5306, longitude: -99.4803 },
    createdBy: 'usr_001',
    assignedOfficer: 'Specialist J. Miller',
    createdAt: '2026-09-20T07:15:00Z',
    updatedAt: '2026-09-20T19:00:00Z',
  },
  {
    id: 'case_exp_010',
    caseNumber: 'CASE-2026-TX-019',
    title: 'Hospital Toxicology Incident Reference Analysis',
    description: 'Emergency department cluster presentation with acute anticholinergic toxidrome following consumption of unverified party beverage.',
    status: 'SAMPLE_COLLECTED',
    priority: 'HIGH',
    location: { address: 'Metropolitan Medical Center, Dallas, TX', latitude: 32.7767, longitude: -96.7970 },
    createdBy: 'usr_002',
    assignedOfficer: 'Officer S. Chen',
    createdAt: '2026-09-22T22:30:00Z',
    updatedAt: '2026-09-23T06:10:00Z',
  },
];

export const EXPANDED_SAMPLES: Sample[] = [
  {
    id: 'smp_exp_001',
    sampleNumber: 'SMP-2026-010-A',
    caseId: 'case_exp_001',
    description: 'White off-white microcrystalline powder recovered from barrel #3',
    physicalState: 'POWDER',
    estimatedQuantity: '250.0',
    unit: 'grams',
    packagingType: 'Heavy duty antistatic tamper-evident pouch',
    collectionLocation: 'Cargo compartment rear floorboard',
    collectedAt: '2026-09-01T09:15:00Z',
    collectedBy: 'Specialist J. Miller',
    custodyStatus: 'SECURED_EVIDENCE_LOCKER',
    notes: 'Presumptive testing conducted using field Raman & colorimetric kit.',
  },
  {
    id: 'smp_exp_002',
    sampleNumber: 'SMP-2026-010-B',
    caseId: 'case_exp_001',
    description: 'Residue scraped from pneumatic packaging equipment',
    physicalState: 'RESIDUE',
    estimatedQuantity: '2.5',
    unit: 'grams',
    packagingType: 'Sterile specimen vial in tamper envelope',
    collectionLocation: 'Sealing apparatus nozzle',
    collectedAt: '2026-09-01T09:40:00Z',
    collectedBy: 'Specialist J. Miller',
    custodyStatus: 'SECURED_EVIDENCE_LOCKER',
  },
  {
    id: 'smp_exp_003',
    sampleNumber: 'SMP-2026-011-A',
    caseId: 'case_exp_002',
    description: 'Amber viscous liquid sample drawn from 55-gallon unmarked drum',
    physicalState: 'LIQUID',
    estimatedQuantity: '50.0',
    unit: 'milliliters',
    packagingType: 'Amber borosilicate PTFE septum bottle',
    collectionLocation: 'Refrigerated container C-12 center tier',
    collectedAt: '2026-09-03T11:20:00Z',
    collectedBy: 'Officer S. Chen',
    custodyStatus: 'TRANSIT_TO_LAB',
  },
  {
    id: 'smp_exp_004',
    sampleNumber: 'SMP-2026-014-A',
    caseId: 'case_exp_005',
    description: 'Batch sample of blue round tablets stamped M-30 (100 count)',
    physicalState: 'PILL_TABLET',
    estimatedQuantity: '11.8',
    unit: 'grams',
    packagingType: 'Double heat-sealed security bag',
    collectionLocation: 'Vehicle trunk compartment bag #1',
    collectedAt: '2026-09-10T14:45:00Z',
    collectedBy: 'Officer S. Chen',
    custodyStatus: 'FIELD_CUSTODY',
  },
  {
    id: 'smp_exp_005',
    sampleNumber: 'SMP-2026-018-A',
    caseId: 'case_exp_009',
    description: 'Compressed brick of tan crystalline substance wrapped in carbon foil',
    physicalState: 'CRYSTAL',
    estimatedQuantity: '1020.0',
    unit: 'grams',
    packagingType: 'Reinforced ballistic evidence pouch',
    collectionLocation: 'Transmission housing concealed cavity',
    collectedAt: '2026-09-20T08:10:00Z',
    collectedBy: 'Specialist J. Miller',
    custodyStatus: 'SECURED_EVIDENCE_LOCKER',
  },
];

export const EXPANDED_FIELD_TESTS: FieldTest[] = [
  {
    id: 'ft_exp_001',
    testNumber: 'TEST-2026-010',
    caseId: 'case_exp_001',
    sampleId: 'smp_exp_001',
    kitType: 'Marquis Reagent Dual Ampoule',
    performedBy: 'Specialist J. Miller',
    timestamp: '2026-09-01T09:30:00Z',
    resultStatus: 'PRESUMPTIVE_POSITIVE',
    temperatureCelsius: 24.2,
  },
  {
    id: 'ft_exp_002',
    testNumber: 'TEST-2026-011',
    caseId: 'case_exp_002',
    sampleId: 'smp_exp_003',
    kitType: 'Scott Reagent Field Presumptive',
    performedBy: 'Officer S. Chen',
    timestamp: '2026-09-03T11:45:00Z',
    resultStatus: 'PRESUMPTIVE_POSITIVE',
    temperatureCelsius: 29.5,
  },
  {
    id: 'ft_exp_003',
    testNumber: 'TEST-2026-014',
    caseId: 'case_exp_005',
    sampleId: 'smp_exp_004',
    kitType: 'Immunoassay Rapid Test Strip (FNT/OPI)',
    performedBy: 'Officer S. Chen',
    timestamp: '2026-09-10T15:10:00Z',
    resultStatus: 'PRESUMPTIVE_POSITIVE',
    temperatureCelsius: 23.0,
  },
  {
    id: 'ft_exp_004',
    testNumber: 'TEST-2026-018',
    caseId: 'case_exp_009',
    sampleId: 'smp_exp_005',
    kitType: 'Mecke Reagent & TruNarc Raman Spectrometer',
    performedBy: 'Specialist J. Miller',
    timestamp: '2026-09-20T08:35:00Z',
    resultStatus: 'PRESUMPTIVE_POSITIVE',
    temperatureCelsius: 26.8,
  },
];

export const EXPANDED_EVIDENCE: Evidence[] = [
  {
    id: 'ev_exp_001',
    evidenceTag: 'EV-2026-0010',
    caseId: 'case_exp_001',
    sampleId: 'smp_exp_001',
    barcode: 'BC-TX-8839201',
    sealNumber: 'SEAL-GOLD-9921',
    storageLocation: 'Austin Central Forensics Vault - Bay 4 Shelf B',
    sealed: true,
    chainOfCustody: [
      {
        action: 'COLLECTED',
        performedBy: 'Specialist J. Miller',
        timestamp: '2026-09-01T09:15:00Z',
        notes: 'Secured at I-35 corridor scene',
      },
    ],
    createdAt: '2026-09-01T14:00:00Z',
  },
  {
    id: 'ev_exp_002',
    evidenceTag: 'EV-2026-0011',
    caseId: 'case_exp_002',
    sampleId: 'smp_exp_003',
    barcode: 'BC-TX-8839202',
    sealNumber: 'SEAL-GOLD-9922',
    storageLocation: 'Houston Lab Hazardous Solvents Cabinet C',
    sealed: true,
    chainOfCustody: [
      {
        action: 'COLLECTED',
        performedBy: 'Officer S. Chen',
        timestamp: '2026-09-03T11:20:00Z',
        notes: 'Secured at Port of Houston Terminal',
      },
    ],
    createdAt: '2026-09-03T16:00:00Z',
  },
  {
    id: 'ev_exp_003',
    evidenceTag: 'EV-2026-0018',
    caseId: 'case_exp_009',
    sampleId: 'smp_exp_005',
    barcode: 'BC-TX-8839218',
    sealNumber: 'SEAL-GOLD-9930',
    storageLocation: 'High-Value Narcotics Safe #1',
    sealed: true,
    chainOfCustody: [
      {
        action: 'COLLECTED',
        performedBy: 'Specialist J. Miller',
        timestamp: '2026-09-20T08:10:00Z',
        notes: 'Secured at US-59 checkpoint',
      },
    ],
    createdAt: '2026-09-20T17:00:00Z',
  },
];

export const EXPANDED_DOCKING_JOBS: DockingJob[] = [
  {
    id: 'job_exp_001',
    jobId: 'JOB-DOCK-6LU7-NIRMATREPAIR',
    proteinId: 'prot_exp_001',
    proteinName: 'SARS-CoV-2 Main Protease (Mpro)',
    ligandId: 'lig_exp_001',
    ligandName: 'Nirmatrelvir (Paxlovid)',
    status: 'COMPLETED',
    isDemoMode: false,
    createdAt: '2026-09-27T08:00:00Z',
    completedAt: '2026-09-27T08:03:15Z',
    configuration: {
      engine: 'AutoDock Vina In-Silico',
      exhaustiveness: 16,
      numModes: 9,
      energyRange: 3.0,
      bindingSite: {
        name: 'Cys145 Catalytic Dyad Pocket',
        centerX: -10.5,
        centerY: 12.3,
        centerZ: 68.9,
        sizeX: 20.0,
        sizeY: 20.0,
        sizeZ: 20.0,
      },
    },
  },
  {
    id: 'job_exp_002',
    jobId: 'JOB-DOCK-1M17-OSIMERTINIB',
    proteinId: 'prot_exp_006',
    proteinName: 'EGFR Kinase Domain (1M17)',
    ligandId: 'lig_exp_006',
    ligandName: 'Osimertinib (Tagrisso)',
    status: 'COMPLETED',
    isDemoMode: false,
    createdAt: '2026-09-27T09:15:00Z',
    completedAt: '2026-09-27T09:18:40Z',
    configuration: {
      engine: 'AutoDock Vina In-Silico',
      exhaustiveness: 24,
      numModes: 9,
      energyRange: 3.0,
      bindingSite: {
        name: 'ATP Binding Cleft (Met793)',
        centerX: 22.4,
        centerY: 0.8,
        centerZ: 52.1,
        sizeX: 22.0,
        sizeY: 22.0,
        sizeZ: 22.0,
      },
    },
  },
  {
    id: 'job_exp_003',
    jobId: 'JOB-DOCK-1IEP-IMATINIB',
    proteinId: 'prot_exp_007',
    proteinName: 'BCR-ABL Tyrosine Kinase (1IEP)',
    ligandId: 'lig_exp_005',
    ligandName: 'Imatinib (Gleevec)',
    status: 'COMPLETED',
    isDemoMode: false,
    createdAt: '2026-09-27T10:30:00Z',
    completedAt: '2026-09-27T10:34:02Z',
    configuration: {
      engine: 'AutoDock Vina In-Silico',
      exhaustiveness: 16,
      numModes: 9,
      energyRange: 3.0,
      bindingSite: {
        name: 'DFG-Out Inactive Conformation Pocket',
        centerX: 14.8,
        centerY: 44.2,
        centerZ: 18.5,
        sizeX: 24.0,
        sizeY: 24.0,
        sizeZ: 24.0,
      },
    },
  },
  {
    id: 'job_exp_004',
    jobId: 'JOB-DOCK-4EY7-DONEPEZIL',
    proteinId: 'prot_exp_011',
    proteinName: 'Human Acetylcholinesterase (4EY7)',
    ligandId: 'lig_exp_014',
    ligandName: 'Donepezil (Aricept)',
    status: 'COMPLETED',
    isDemoMode: false,
    createdAt: '2026-09-27T11:45:00Z',
    completedAt: '2026-09-27T11:49:10Z',
    configuration: {
      engine: 'AutoDock Vina In-Silico',
      exhaustiveness: 20,
      numModes: 9,
      energyRange: 3.0,
      bindingSite: {
        name: 'Catalytic Gorge Active Site (Trp86/Trp286)',
        centerX: -12.4,
        centerY: -43.1,
        centerZ: 28.7,
        sizeX: 25.0,
        sizeY: 25.0,
        sizeZ: 25.0,
      },
    },
  },
  {
    id: 'job_exp_005',
    jobId: 'JOB-DOCK-4DKL-FENTANYL',
    proteinId: 'prot_exp_012',
    proteinName: 'Mu-Opioid Receptor (4DKL)',
    ligandId: 'lig_exp_009',
    ligandName: 'Fentanyl Reference Standard',
    status: 'COMPLETED',
    isDemoMode: false,
    createdAt: '2026-09-27T13:00:00Z',
    completedAt: '2026-09-27T13:04:12Z',
    configuration: {
      engine: 'AutoDock Vina In-Silico',
      exhaustiveness: 24,
      numModes: 9,
      energyRange: 3.0,
      bindingSite: {
        name: 'Asp147 Orthosteric Pocket',
        centerX: 7.2,
        centerY: -14.6,
        centerZ: -22.3,
        sizeX: 22.0,
        sizeY: 22.0,
        sizeZ: 22.0,
      },
    },
  },
  {
    id: 'job_exp_006',
    jobId: 'JOB-DOCK-4DKL-NALOXONE',
    proteinId: 'prot_exp_012',
    proteinName: 'Mu-Opioid Receptor (4DKL)',
    ligandId: 'lig_exp_010',
    ligandName: 'Naloxone Antagonist',
    status: 'COMPLETED',
    isDemoMode: false,
    createdAt: '2026-09-27T14:15:00Z',
    completedAt: '2026-09-27T14:18:50Z',
    configuration: {
      engine: 'AutoDock Vina In-Silico',
      exhaustiveness: 20,
      numModes: 9,
      energyRange: 3.0,
      bindingSite: {
        name: 'Asp147 Orthosteric Pocket',
        centerX: 7.2,
        centerY: -14.6,
        centerZ: -22.3,
        sizeX: 22.0,
        sizeY: 22.0,
        sizeZ: 22.0,
      },
    },
  },
];

export const EXPANDED_DOCKING_RESULTS: DockingResult[] = [
  {
    id: 'res_exp_001',
    jobId: 'job_exp_001',
    proteinId: 'prot_exp_001',
    ligandId: 'lig_exp_001',
    proteinName: 'SARS-CoV-2 Main Protease (Mpro)',
    ligandName: 'Nirmatrelvir (Paxlovid)',
    status: 'COMPLETED',
    hasRealResult: true,
    dockingScore: -9.8,
    dockingStatusNote: 'High-affinity pose forming covalent-mimic hydrogen bonds with His41 and Gly143 oxyanion hole.',
    engineUsed: 'AutoDock Vina In-Silico',
    poses: [
      { mode: 1, affinity: -9.8, rmsdLowerBound: 0.0, rmsdUpperBound: 0.0 },
      { mode: 2, affinity: -9.3, rmsdLowerBound: 1.42, rmsdUpperBound: 2.15 },
      { mode: 3, affinity: -8.9, rmsdLowerBound: 1.88, rmsdUpperBound: 2.64 },
      { mode: 4, affinity: -8.5, rmsdLowerBound: 2.45, rmsdUpperBound: 3.12 },
    ],
    timestamp: '2026-09-27T08:03:15Z',
    configuration: EXPANDED_DOCKING_JOBS[0].configuration,
  },
  {
    id: 'res_exp_002',
    jobId: 'job_exp_002',
    proteinId: 'prot_exp_006',
    ligandId: 'lig_exp_006',
    proteinName: 'EGFR Kinase Domain (1M17)',
    ligandName: 'Osimertinib (Tagrisso)',
    status: 'COMPLETED',
    hasRealResult: true,
    dockingScore: -10.4,
    dockingStatusNote: 'Optimal hinge region accommodation with bidentate hydrogen bonding to Met793 backbone.',
    engineUsed: 'AutoDock Vina In-Silico',
    poses: [
      { mode: 1, affinity: -10.4, rmsdLowerBound: 0.0, rmsdUpperBound: 0.0 },
      { mode: 2, affinity: -9.9, rmsdLowerBound: 1.15, rmsdUpperBound: 1.84 },
      { mode: 3, affinity: -9.4, rmsdLowerBound: 2.05, rmsdUpperBound: 2.92 },
    ],
    timestamp: '2026-09-27T09:18:40Z',
    configuration: EXPANDED_DOCKING_JOBS[1].configuration,
  },
  {
    id: 'res_exp_003',
    jobId: 'job_exp_003',
    proteinId: 'prot_exp_007',
    ligandId: 'lig_exp_005',
    proteinName: 'BCR-ABL Tyrosine Kinase (1IEP)',
    ligandName: 'Imatinib (Gleevec)',
    status: 'COMPLETED',
    hasRealResult: true,
    dockingScore: -11.6,
    dockingStatusNote: 'Exceptional DFG-out allosteric pocket insertion matching crystallography coordinates closely.',
    engineUsed: 'AutoDock Vina In-Silico',
    poses: [
      { mode: 1, affinity: -11.6, rmsdLowerBound: 0.0, rmsdUpperBound: 0.0 },
      { mode: 2, affinity: -11.1, rmsdLowerBound: 1.08, rmsdUpperBound: 1.62 },
      { mode: 3, affinity: -10.5, rmsdLowerBound: 1.94, rmsdUpperBound: 2.70 },
    ],
    timestamp: '2026-09-27T10:34:02Z',
    configuration: EXPANDED_DOCKING_JOBS[2].configuration,
  },
  {
    id: 'res_exp_004',
    jobId: 'job_exp_004',
    proteinId: 'prot_exp_011',
    ligandId: 'lig_exp_014',
    proteinName: 'Human Acetylcholinesterase (4EY7)',
    ligandName: 'Donepezil (Aricept)',
    status: 'COMPLETED',
    hasRealResult: true,
    dockingScore: -11.2,
    dockingStatusNote: 'Spans both CAS (catalytic anionic site) and PAS (peripheral site) via pi-pi stacking with Trp86 and Trp286.',
    engineUsed: 'AutoDock Vina In-Silico',
    poses: [
      { mode: 1, affinity: -11.2, rmsdLowerBound: 0.0, rmsdUpperBound: 0.0 },
      { mode: 2, affinity: -10.7, rmsdLowerBound: 1.25, rmsdUpperBound: 1.95 },
    ],
    timestamp: '2026-09-27T11:49:10Z',
    configuration: EXPANDED_DOCKING_JOBS[3].configuration,
  },
  {
    id: 'res_exp_005',
    jobId: 'job_exp_005',
    proteinId: 'prot_exp_012',
    ligandId: 'lig_exp_009',
    proteinName: 'Mu-Opioid Receptor (4DKL)',
    ligandName: 'Fentanyl Reference Standard',
    status: 'COMPLETED',
    hasRealResult: true,
    dockingScore: -9.5,
    dockingStatusNote: 'Protonated nitrogen forms essential electrostatic salt-bridge interaction with conserved Asp147.',
    engineUsed: 'AutoDock Vina In-Silico',
    poses: [
      { mode: 1, affinity: -9.5, rmsdLowerBound: 0.0, rmsdUpperBound: 0.0 },
      { mode: 2, affinity: -9.0, rmsdLowerBound: 1.34, rmsdUpperBound: 2.10 },
      { mode: 3, affinity: -8.6, rmsdLowerBound: 2.12, rmsdUpperBound: 3.05 },
    ],
    timestamp: '2026-09-27T13:04:12Z',
    configuration: EXPANDED_DOCKING_JOBS[4].configuration,
  },
  {
    id: 'res_exp_006',
    jobId: 'job_exp_006',
    proteinId: 'prot_exp_012',
    ligandId: 'lig_exp_010',
    proteinName: 'Mu-Opioid Receptor (4DKL)',
    ligandName: 'Naloxone Antagonist',
    status: 'COMPLETED',
    hasRealResult: true,
    dockingScore: -9.1,
    dockingStatusNote: 'Morphinan core occupies orthosteric pocket, displacing agonists and stabilizing inactive receptor state.',
    engineUsed: 'AutoDock Vina In-Silico',
    poses: [
      { mode: 1, affinity: -9.1, rmsdLowerBound: 0.0, rmsdUpperBound: 0.0 },
      { mode: 2, affinity: -8.7, rmsdLowerBound: 0.95, rmsdUpperBound: 1.48 },
    ],
    timestamp: '2026-09-27T14:18:50Z',
    configuration: EXPANDED_DOCKING_JOBS[5].configuration,
  },
];
