/**
 * =========================================================================
 * DEMO SEED DATA - FOR EVALUATION & PROTOTYPING PURPOSES ONLY
 * =========================================================================
 * This data contains simulated, realistic field operation records
 * for authorized regulatory, laboratory, and field test verification.
 * NO illicit formulas, concealment, or operational hazard advice is contained.
 */

import type {
  User,
  Case,
  FieldTest,
  Sample,
  Evidence,
  TestResult,
  Report,
  SyncRecord,
  AuditLog,
  Protein,
  Ligand,
} from '../types';
import {
  STRUCTURE_1HSG,
  STRUCTURE_6LU7,
  LIGAND_1HSG_MK1,
  LIGAND_6LU7_N3,
} from './defaultStructures';

export const DEMO_USERS: User[] = [
  {
    id: 'usr_admin',
    username: 'admin.reyes',
    fullName: 'Commander R. Reyes',
    badgeNumber: 'ADM-001',
    agency: 'State Department of Forensic Oversight',
    role: 'ADMIN',
    email: 'admin@forensics.agency.gov',
    active: true,
    createdAt: '2025-10-01T08:00:00Z',
  },
  {
    id: 'usr_001',
    username: 'j.miller',
    fullName: 'Specialist J. Miller',
    badgeNumber: 'TX-4921',
    agency: 'State Bureau of Forensic Operations',
    role: 'FIELD_OFFICER',
    email: 'j.miller@forensics.agency.gov',
    active: true,
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'usr_003',
    username: 'm.vance',
    fullName: 'Supervisor M. Vance',
    badgeNumber: 'SUP-1044',
    agency: 'Special Investigations Taskforce',
    role: 'SUPERVISOR',
    email: 'm.vance@forensics.agency.gov',
    active: true,
    createdAt: '2025-11-20T10:00:00Z',
  },
  {
    id: 'usr_002',
    username: 's.chen',
    fullName: 'Dr. Sarah Chen',
    badgeNumber: 'LAB-8812',
    agency: 'Central Forensic Laboratory',
    role: 'LAB_USER',
    email: 's.chen@lab.agency.gov',
    active: true,
    createdAt: '2026-01-10T09:30:00Z',
  },
  {
    id: 'usr_viewer',
    username: 'v.taylor',
    fullName: 'Inspector V. Taylor',
    badgeNumber: 'AUD-552',
    agency: 'Compliance & Oversight Commission',
    role: 'VIEWER',
    email: 'v.taylor@audit.agency.gov',
    active: true,
    createdAt: '2026-02-01T09:00:00Z',
  },
];

export const DEMO_CASES: Case[] = [
  {
    id: 'case_2026_089',
    caseNumber: 'FT-2026-0001',
    title: 'Interstate Transport Inspection - Checkpoint North',
    status: 'IN_PROGRESS',
    incidentDate: '2026-09-28T14:30:00Z',
    location: {
      address: 'Mile Marker 142, Northbound I-35 Corridor',
      latitude: 32.7767,
      longitude: -96.797,
    },
    createdBy: 'Specialist J. Miller',
    assignedOfficer: 'Specialist J. Miller',
    leadOfficerId: 'usr_001',
    leadOfficerName: 'Specialist J. Miller',
    agency: 'State Bureau of Forensic Operations',
    priority: 'HIGH',
    description: 'Routine commercial motor vehicle compliance screening. Suspicious unlabeled crystalline containers flagged during cargo manifest verification.',
    notes: 'Presumptive colorimetric series initiated on scene. Split sample prepped for lab intake.',
    isArchived: false,
    createdAt: '2026-09-28T14:45:00Z',
    updatedAt: '2026-09-29T09:15:00Z',
  },
  {
    id: 'case_2026_090',
    caseNumber: 'FT-2026-0002',
    title: 'Warehouse Customs & Border Compliance Intake',
    status: 'OPEN',
    incidentDate: '2026-09-29T11:00:00Z',
    location: {
      address: 'Dock 4, Terminal West Logistics Hub',
      latitude: 32.8998,
      longitude: -97.0403,
    },
    createdBy: 'Specialist J. Miller',
    assignedOfficer: 'Specialist J. Miller',
    leadOfficerId: 'usr_001',
    leadOfficerName: 'Specialist J. Miller',
    agency: 'State Bureau of Forensic Operations',
    priority: 'MEDIUM',
    description: 'Imported biological & chemical precursor shipment verification. Discrepancy between declared botanical extract and packaging labels.',
    notes: 'Awaiting specialized solvent extraction field kit test.',
    isArchived: false,
    createdAt: '2026-09-29T11:20:00Z',
    updatedAt: '2026-09-29T16:00:00Z',
  },
  {
    id: 'case_2026_088',
    caseNumber: 'FT-2026-0003',
    title: 'Harbor Freight Cargo Manifest Examination',
    status: 'UNDER_REVIEW',
    incidentDate: '2026-09-27T08:15:00Z',
    location: {
      address: 'Pier 12 Customs Inspection Bay',
      latitude: 29.3013,
      longitude: -94.7977,
    },
    createdBy: 'Supervisor M. Vance',
    assignedOfficer: 'Supervisor M. Vance',
    leadOfficerId: 'usr_003',
    leadOfficerName: 'Supervisor M. Vance',
    agency: 'Special Investigations Taskforce',
    priority: 'CRITICAL',
    description: 'Container sealed with non-standard security ties. Presumptive field testing completed, awaiting secondary supervisor sign-off.',
    notes: 'Presumptive cannabinoid profile verified with Duquenois-Levine reagent.',
    isArchived: false,
    createdAt: '2026-09-27T08:45:00Z',
    updatedAt: '2026-09-30T10:00:00Z',
  },
  {
    id: 'case_2026_079',
    caseNumber: 'FT-2026-0004',
    title: 'Suburban Parcel Depot Interception',
    status: 'CLOSED',
    incidentDate: '2026-09-20T16:00:00Z',
    location: {
      address: 'Central Sorting Facility Bay 9',
      latitude: 30.2672,
      longitude: -97.7431,
    },
    createdBy: 'Specialist J. Miller',
    assignedOfficer: 'Specialist J. Miller',
    leadOfficerId: 'usr_001',
    leadOfficerName: 'Specialist J. Miller',
    agency: 'State Bureau of Forensic Operations',
    priority: 'LOW',
    description: 'Suspected unknown compound submitted for field reagent test. Presumptive negative; verified harmless industrial additive.',
    notes: 'Case completed and archived in compliance with regulatory protocol.',
    isArchived: false,
    createdAt: '2026-09-20T16:20:00Z',
    updatedAt: '2026-09-25T14:10:00Z',
  },
];

export const DEMO_SAMPLES: Sample[] = [
  {
    id: 'smp_001',
    sampleNumber: 'SMP-2026-089-A',
    caseId: 'case_2026_089',
    description: 'White granular crystalline substance inside vacuum sealed pouch',
    physicalState: 'CRYSTAL',
    estimatedQuantity: '450',
    unit: 'grams',
    packagingType: 'Heavy gauge heat-sealed polymer bag',
    collectionLocation: 'Secondary inspection trunk storage compartment',
    collectedAt: '2026-09-28T15:05:00Z',
    collectedBy: 'Specialist J. Miller',
    custodyStatus: 'TRANSIT_TO_LAB',
    notes: 'Sample split into primary field vial and confirmatory laboratory split.',
  },
  {
    id: 'smp_002',
    sampleNumber: 'SMP-2026-089-B',
    caseId: 'case_2026_089',
    description: 'Compressed off-white pressed tablets with scored marking',
    physicalState: 'PILL_TABLET',
    estimatedQuantity: '120',
    unit: 'units',
    packagingType: 'Amber HDPE pharmaceutical container',
    collectionLocation: 'Glove compartment lockbox',
    collectedAt: '2026-09-28T15:20:00Z',
    collectedBy: 'Specialist J. Miller',
    custodyStatus: 'FIELD_CUSTODY',
    notes: 'Presumptive colorimetric test completed in field.',
  },
  {
    id: 'smp_003',
    sampleNumber: 'SMP-2026-090-A',
    caseId: 'case_2026_090',
    description: 'Amber viscous fluid in amber glass ampoule',
    physicalState: 'LIQUID',
    estimatedQuantity: '50',
    unit: 'ml',
    packagingType: 'Sealed glass bottle with tamper strip',
    collectionLocation: 'Crate pallet 14, manifest item 03',
    collectedAt: '2026-09-29T11:45:00Z',
    collectedBy: 'Specialist J. Miller',
    custodyStatus: 'SECURED_EVIDENCE_LOCKER',
    notes: 'Awaiting specialized solvent extraction kit test.',
  },
  {
    id: 'smp_004',
    sampleNumber: 'SMP-2026-088-A',
    caseId: 'case_2026_088',
    description: 'Greenish-brown dried botanical material',
    physicalState: 'PLANT_MATERIAL',
    estimatedQuantity: '1200',
    unit: 'grams',
    packagingType: 'Double-walled paper evidence sack',
    collectionLocation: 'Cargo container 8821 floor section',
    collectedAt: '2026-09-27T09:10:00Z',
    collectedBy: 'Supervisor M. Vance',
    custodyStatus: 'TRANSIT_TO_LAB',
    notes: 'Duquenois-Levine reagent field test administered.',
  },
];

export const DEMO_FIELD_TESTS: FieldTest[] = [
  {
    id: 'tst_001',
    testNumber: 'TEST-2026-001',
    caseId: 'case_2026_089',
    sampleId: 'smp_001',
    kitType: 'Colorimetric Reagent Ampoule Series A',
    performedBy: 'Specialist J. Miller',
    timestamp: '2026-09-28T15:35:00Z',
    resultStatus: 'PRESUMPTIVE_POSITIVE',
    presumptiveCategory: 'Alkaloid Target Class I (Presumptive)',
    confidenceRating: 'HIGH',
    temperatureCelsius: 22.4,
    notes: 'Rapid blue precipitate reaction observed within 8 seconds.',
    photoAttached: true,
  },
  {
    id: 'tst_002',
    testNumber: 'TEST-2026-002',
    caseId: 'case_2026_089',
    sampleId: 'smp_002',
    kitType: 'Lateral Flow Immunoassay Strip Kit',
    performedBy: 'Specialist J. Miller',
    timestamp: '2026-09-28T15:50:00Z',
    resultStatus: 'PRESUMPTIVE_POSITIVE',
    presumptiveCategory: 'Synthetic Stimulant Group B (Presumptive)',
    confidenceRating: 'MEDIUM',
    temperatureCelsius: 23.0,
    notes: 'Dual band validation line confirmed within 5 minutes.',
    photoAttached: true,
  },
  {
    id: 'tst_003',
    testNumber: 'TEST-2026-003',
    caseId: 'case_2026_088',
    sampleId: 'smp_004',
    kitType: 'Modified Duquenois-Levine Field Kit',
    performedBy: 'Supervisor M. Vance',
    timestamp: '2026-09-27T09:40:00Z',
    resultStatus: 'PRESUMPTIVE_POSITIVE',
    presumptiveCategory: 'Cannabinoid Profile (Presumptive)',
    confidenceRating: 'HIGH',
    temperatureCelsius: 21.0,
    notes: 'Violet layer separation noted in lower chloroform phase.',
    photoAttached: true,
  },
  {
    id: 'tst_004',
    testNumber: 'TEST-2026-004',
    caseId: 'case_2026_079',
    sampleId: 'smp_003',
    kitType: 'General Screening Multi-Reagent Panel',
    performedBy: 'Specialist J. Miller',
    timestamp: '2026-09-20T16:45:00Z',
    resultStatus: 'PRESUMPTIVE_NEGATIVE',
    presumptiveCategory: 'Non-reactive / Inactive Buffer',
    confidenceRating: 'HIGH',
    temperatureCelsius: 24.1,
    notes: 'No chromogenic reaction after 120 seconds.',
    photoAttached: false,
  },
];

export const DEMO_EVIDENCE: Evidence[] = [
  {
    id: 'evi_001',
    evidenceTag: 'EV-2026-089-01',
    caseId: 'case_2026_089',
    sampleId: 'smp_001',
    barcode: 'BC982144701',
    sealed: true,
    sealNumber: 'SEAL-TX-99014',
    storageLocation: 'Field Unit Mobile Secure Safe #2',
    createdAt: '2026-09-28T15:10:00Z',
    chainOfCustody: [
      {
        action: 'Initial Field Collection & Sealing',
        performedBy: 'Specialist J. Miller',
        timestamp: '2026-09-28T15:10:00Z',
        destinationLocation: 'Field Vehicle Transport Bin',
        notes: 'Tamper-evident seal applied in presence of witness.',
      },
      {
        action: 'Transfer to Secure Mobile Vault',
        performedBy: 'Specialist J. Miller',
        timestamp: '2026-09-28T16:00:00Z',
        destinationLocation: 'Field Unit Mobile Secure Safe #2',
        notes: 'Checked temperature and seal integrity.',
      },
    ],
  },
  {
    id: 'evi_002',
    evidenceTag: 'EV-2026-089-02',
    caseId: 'case_2026_089',
    sampleId: 'smp_002',
    barcode: 'BC982144702',
    sealed: true,
    sealNumber: 'SEAL-TX-99015',
    storageLocation: 'Field Unit Mobile Secure Safe #2',
    createdAt: '2026-09-28T15:25:00Z',
    chainOfCustody: [
      {
        action: 'Initial Field Packaging & Barcode Generation',
        performedBy: 'Specialist J. Miller',
        timestamp: '2026-09-28T15:25:00Z',
        destinationLocation: 'Field Unit Mobile Secure Safe #2',
      },
    ],
  },
];

export const DEMO_TEST_RESULTS: TestResult[] = [
  {
    id: 'res_001',
    fieldTestId: 'tst_001',
    sampleId: 'smp_001',
    analyteTarget: 'Primary Organic Alkaloids',
    primaryReaction: 'Cobalt thiocyanate intense blue complex',
    outcome: 'PRESUMPTIVE_POSITIVE',
    verifiedBySupervisor: true,
    supervisorNotes: 'Reaction color conforms to manufacturer reference chart 3A.',
    recordedAt: '2026-09-28T15:36:00Z',
  },
  {
    id: 'res_002',
    fieldTestId: 'tst_002',
    sampleId: 'smp_002',
    analyteTarget: 'Synthetic Phenethylamine Class',
    primaryReaction: 'Membrane test line suppression (positive threshold)',
    outcome: 'PRESUMPTIVE_POSITIVE',
    verifiedBySupervisor: false,
    recordedAt: '2026-09-28T15:52:00Z',
  },
];

export const DEMO_REPORTS: Report[] = [
  {
    id: 'rep_001',
    reportNumber: 'REP-2026-089-F',
    caseId: 'case_2026_089',
    title: 'Preliminary Field Incident & Presumptive Screening Report',
    type: 'FIELD_SUMMARY',
    generatedBy: 'Specialist J. Miller',
    generatedAt: '2026-09-28T17:15:00Z',
    summary: 'Two suspected items cataloged and screened via presumptive colorimetric and immunoassay methods. Presumptive positive results noted. Confirmatory GC-MS requested.',
    status: 'FINALIZED',
    exportFormat: 'PDF',
  },
  {
    id: 'rep_002',
    reportNumber: 'REP-2026-088-C',
    caseId: 'case_2026_088',
    title: 'Chain of Custody Transfer Manifest',
    type: 'CHAIN_OF_CUSTODY',
    generatedBy: 'Supervisor M. Vance',
    generatedAt: '2026-09-27T11:00:00Z',
    summary: 'Evidence items EV-2026-088-01 prepped for secure courier transfer to regional laboratory repository.',
    status: 'SUBMITTED',
    exportFormat: 'PDF',
  },
];

export const DEMO_SYNC_RECORDS: SyncRecord[] = [
  {
    id: 'sync_001',
    entityType: 'fieldTests',
    entityId: 'tst_002',
    action: 'CREATE',
    payload: JSON.stringify({ testNumber: 'TEST-2026-002', sampleId: 'smp_002' }),
    status: 'PENDING',
    attempts: 0,
    createdAt: '2026-09-28T15:50:00Z',
  },
  {
    id: 'sync_002',
    entityType: 'samples',
    entityId: 'smp_003',
    action: 'CREATE',
    payload: JSON.stringify({ sampleNumber: 'SMP-2026-090-A' }),
    status: 'PENDING',
    attempts: 1,
    lastAttemptAt: '2026-09-29T12:00:00Z',
    error: 'Remote endpoint timed out during field cell reconnect',
    createdAt: '2026-09-29T11:45:00Z',
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_001',
    action: 'SYSTEM_INITIALIZATION',
    entityType: 'SYSTEM',
    entityId: 'SYSTEM',
    performedBy: 'Specialist J. Miller',
    userRole: 'FIELD_OFFICER',
    timestamp: '2026-09-28T14:30:00Z',
    details: 'Encrypted offline store initialized on field terminal',
    integrityHash: 'sha256-8a7e0f214bc74d',
  },
  {
    id: 'aud_002',
    action: 'CASE_RECORD_CREATED',
    entityType: 'Case',
    entityId: 'case_2026_089',
    performedBy: 'Specialist J. Miller',
    userRole: 'FIELD_OFFICER',
    timestamp: '2026-09-28T14:45:00Z',
    details: 'Case CASE-2026-089 opened with priority HIGH',
    integrityHash: 'sha256-42bb33f9901ad',
  },
  {
    id: 'aud_003',
    action: 'SAMPLE_REGISTERED',
    entityType: 'Sample',
    entityId: 'smp_001',
    performedBy: 'Specialist J. Miller',
    userRole: 'FIELD_OFFICER',
    timestamp: '2026-09-28T15:05:00Z',
    details: 'Sample SMP-2026-089-A cataloged under chain of custody',
    integrityHash: 'sha256-99c01ffea341e',
  },
  {
    id: 'aud_004',
    action: 'FIELD_TEST_LOGGED',
    entityType: 'FieldTest',
    entityId: 'tst_001',
    performedBy: 'Specialist J. Miller',
    userRole: 'FIELD_OFFICER',
    timestamp: '2026-09-28T15:35:00Z',
    details: 'Presumptive test TEST-2026-001 executed: PRESUMPTIVE_POSITIVE',
    integrityHash: 'sha256-11f84cd290bca',
  },
];

/**
 * =========================================================================
 * DEMO PROTEINS (TARGET RECEPTORS)
 * =========================================================================
 */
export const DEMO_PROTEINS: Protein[] = [
  {
    id: 'prot_demo_001',
    name: 'SARS-CoV-2 Main Protease (Mpro)',
    structureId: '6LU7',
    description: 'Crystal structure of main protease in complex with peptide-like inhibitor N3. Essential homodimeric cysteine protease required for processing viral polyproteins.',
    source: 'RCSB PDB Reference (PDB ID: 6LU7)',
    fileName: '6LU7_prepared.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 348210,
    fileData: STRUCTURE_6LU7,
    uploadDate: '2026-09-15T10:00:00Z',
    status: 'READY',
    organism: 'Severe acute respiratory syndrome coronavirus 2',
    resolution: '2.16 Å',
  },
  {
    id: 'prot_demo_002',
    name: 'HIV-1 Retropepsin Protease',
    structureId: '1HSG',
    description: 'Crystal structure of HIV-1 protease complexed with Indinavir. Classic homodimeric aspartic protease target for structure-based drug discovery.',
    source: 'RCSB PDB Reference (PDB ID: 1HSG)',
    fileName: '1HSG_receptor.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 284100,
    fileData: STRUCTURE_1HSG,
    uploadDate: '2026-09-16T14:30:00Z',
    status: 'READY',
    organism: 'Human immunodeficiency virus 1',
    resolution: '2.00 Å',
  },
];

/**
 * =========================================================================
 * DEMO CANDIDATE MOLECULES (LIGANDS)
 * Notice: Strictly labeled as DEMO candidates for computational prototype.
 * =========================================================================
 */
export const DEMO_LIGANDS: Ligand[] = [
  {
    id: 'lig_demo_001',
    name: 'Drug A (Candidate Lead)',
    chemicalName: 'Synthetic Peptidomimetic Core Alpha',
    formula: 'C28H34N4O6',
    molecularWeight: 522.6,
    smiles: 'CC(C)CC(NC(=O)C(CC1=CC=CC=C1)NC(=O)OCC2=CC=CC=C2)C(=O)NC(CC3=CC=CC=C3)C(=O)N',
    fileName: 'candidate_drug_a.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 1845,
    fileData: LIGAND_6LU7_N3,
    isDemo: true,
    uploadDate: '2026-09-20T08:00:00Z',
    status: 'READY',
    description: '[DEMO CANDIDATE] Synthetic protease inhibitor lead analog for computational simulation and tactile 3D physical demonstration.',
  },
  {
    id: 'lig_demo_002',
    name: 'Drug B (Candidate Variant)',
    chemicalName: 'Modified Indole Carboxamide Derivative',
    formula: 'C25H29N3O4',
    molecularWeight: 435.5,
    smiles: 'CC1=C(C2=CC=CC=C2N1)C(=O)NC(CC3=CNC4=CC=CC=C43)C(=O)NC(C)C',
    fileName: 'candidate_drug_b.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 1620,
    fileData: LIGAND_1HSG_MK1,
    isDemo: true,
    uploadDate: '2026-09-20T08:15:00Z',
    status: 'READY',
    description: '[DEMO CANDIDATE] Structural variant designed to evaluate steric tolerance and hydrogen bonding in the S1/S2 active site pocket.',
  },
  {
    id: 'lig_demo_003',
    name: 'Drug C (Reference Control)',
    chemicalName: 'Non-binding Bulky Phenolic Control',
    formula: 'C32H40O8',
    molecularWeight: 552.7,
    smiles: 'COC1=CC(=CC(=C1O)OC)C(=O)OCC2C(C(C(C(O2)OC3=CC(=CC(=C3O)OC)C(=O)O)O)O)O',
    fileName: 'candidate_drug_c.pdbqt',
    fileFormat: 'PDBQT',
    fileSize: 1990,
    fileData: LIGAND_1HSG_MK1,
    isDemo: true,
    uploadDate: '2026-09-20T08:30:00Z',
    status: 'READY',
    description: '[DEMO CANDIDATE] Reference control molecule used to calibrate baseline scoring and demonstrate tactile non-fit in the physical model.',
  },
];

